/* tslint:disable */
/* eslint-disable */
/**
 * base application
 * Proyecto API encargado de ser la parte Backend de la aplicación web base
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: acaicedo@dynamizatic.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export * from "./api";
export * from "./configuration";

